# Generated by Django 4.2.7 on 2023-11-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('date', models.TextField(max_length=12)),
            ],
        ),
    ]
